/** This holds an small extract from paal.

    PAAL is by Piotr Wygocki (wygos at mimuw.edu.pl).
    With a page at https://paal.mimuw.edu.pl/
    And repo URL: http://siekiera.mimuw.edu.pl:8082/paal
    It is licensed under the BOOST License 1.0.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
 */


#ifndef WIRECELLCLUS_PAAL
#define WIRECELLCLUS_PAAL

namespace WireCell::Clus::PAAL {

    struct less {
        /**
         * @brief operator()
         *
         * @tparam T
         * @param x
         * @param y
         *
         * @return
         */
        template <class T>
        auto operator()(const T &x, const T &y) const->decltype(x < y) {
            return x < y;
        }
    };

    template <typename NearestMap, typename LastEdgeMap, typename Tag>
    class nearest_recorder
        : boost::base_visitor<nearest_recorder<NearestMap, LastEdgeMap, Tag>> {
    public:
        using event_filter = Tag;
        nearest_recorder(NearestMap &nearest_map, LastEdgeMap &vpred)
            : m_nearest_map(nearest_map), m_vpred(vpred) {};
        template <typename Edge, typename Graph>
        void operator()(Edge const e, Graph const &g) {
            m_nearest_map[target(e, g)] = m_nearest_map[source(e, g)];
            m_vpred[target(e, g)] = e;
        }

    private:
        NearestMap &m_nearest_map;
        LastEdgeMap &m_vpred;
    };

    template <typename NearestMap, typename LastEdgeMap, typename Tag>
    nearest_recorder<NearestMap, LastEdgeMap, Tag>
    make_nearest_recorder(NearestMap &nearest_map, LastEdgeMap &vpred, Tag) {
        return nearest_recorder<NearestMap, LastEdgeMap, Tag>{ nearest_map, vpred };
    }

}

#endif
